2025-02-25 17:28:56,621 - INFO - Starting Application...
2025-02-25 17:28:56,626 - INFO - Validating dataset_one with Pydantic.
2025-02-25 17:29:00,196 - ERROR - 1 validation error for EmployeeExpertiseCalls
calls_made
  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-54, input_type=int]
    For further information visit https://errors.pydantic.dev/2.10/v/greater_than_equal | Row: {'id': 1, 'area': 'IT', 'calls_made': -54, 'calls_successful': 41} 
2025-02-25 17:29:00,196 - ERROR - 'NoneType' object has no attribute 'lower' | Row: {'id': 6, 'area': None, 'calls_made': 29, 'calls_successful': 24} 
2025-02-25 17:29:00,204 - WARNING -  A total of 2 invalid records excluded from dataset dataset_one
2025-02-25 17:29:00,304 - INFO - Validating dataset_two with Pydantic.
2025-02-25 17:29:00,523 - WARNING -  A total of 0 invalid records excluded from dataset dataset_two
2025-02-25 17:29:00,626 - INFO - Processing outputs.
2025-02-25 17:29:00,853 - INFO - Output it_data is being written to C:\Users\be_al\Github\abn_amro\src\sales_data\..\..\data\output/it_data
2025-02-25 17:29:14,686 - INFO - Output marketing_address_info is being written to C:\Users\be_al\Github\abn_amro\src\sales_data\..\..\data\output/marketing_address_info
2025-02-25 17:29:25,928 - INFO - Closing Application...
2025-02-25 17:29:25,939 - INFO - Closing down clientserver connection
2025-02-25 18:36:39,875 - INFO - Starting Application...
2025-02-25 18:36:39,877 - INFO - Validating dataset_one with Pydantic.
2025-02-25 18:36:47,475 - ERROR - 1 validation error for EmployeeExpertiseCalls
calls_made
  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-54, input_type=int]
    For further information visit https://errors.pydantic.dev/2.10/v/greater_than_equal | Row: {'id': 1, 'area': 'IT', 'calls_made': -54, 'calls_successful': 41} 
2025-02-25 18:36:47,477 - ERROR - 'NoneType' object has no attribute 'lower' | Row: {'id': 6, 'area': None, 'calls_made': 29, 'calls_successful': 24} 
2025-02-25 18:36:47,479 - WARNING - A total of 2 invalid records excluded from dataset dataset_one
2025-02-25 18:36:47,614 - INFO - Validating dataset_two with Pydantic.
2025-02-25 18:36:47,938 - INFO - There were no records excluded from dataset dataset_two
2025-02-25 18:36:48,025 - INFO - Processing outputs.
2025-02-25 18:36:48,187 - INFO - Processing agents selling IT products. Total rows:DataFrame[area: string, calls_made: bigint, calls_successful: bigint, id: bigint, address: string, emp_id: bigint, name: string, sales_amount: double]
2025-02-25 18:37:34,119 - INFO - Successfully processed top 100 agents selling IT products: 100 records
2025-02-25 18:37:34,119 - INFO - Output it_data is being written to data/output/it_data
2025-02-25 18:37:52,800 - INFO - Processing marketing_adress_info output.
2025-02-25 18:37:52,867 - INFO - Output marketing_address_info is being written to data/output/marketing_address_info
2025-02-25 18:38:10,946 - INFO - Closing Application...
2025-02-25 18:38:10,964 - INFO - Closing down clientserver connection
2025-02-25 19:02:18,296 - INFO - Starting Application...
2025-02-25 19:02:18,296 - INFO - Validating dataset_one with Pydantic.
2025-02-25 19:02:25,655 - ERROR - 1 validation error for EmployeeExpertiseCalls
calls_made
  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-54, input_type=int]
    For further information visit https://errors.pydantic.dev/2.10/v/greater_than_equal | Row: {'id': 1, 'area': 'IT', 'calls_made': -54, 'calls_successful': 41} 
2025-02-25 19:02:25,655 - ERROR - 'NoneType' object has no attribute 'lower' | Row: {'id': 6, 'area': None, 'calls_made': 29, 'calls_successful': 24} 
2025-02-25 19:02:25,663 - WARNING - A total of 2 invalid records excluded from dataset dataset_one
2025-02-25 19:02:25,868 - INFO - Validating dataset_two with Pydantic.
2025-02-25 19:02:26,368 - INFO - There were no invalid records found in dataset_two
2025-02-25 19:02:26,481 - INFO - Processing outputs sequentially...
2025-02-25 19:02:26,622 - INFO - Processing it_data output...
2025-02-25 19:02:47,716 - INFO - Successfully processed top 100 agents selling IT products.
2025-02-25 19:02:47,716 - INFO - Output it_data is being written to data/output/it_data
2025-02-25 19:03:04,950 - INFO - Processing marketing_adress_info output...
2025-02-25 19:03:05,002 - INFO - Output marketing_address_info is being written to data/output/marketing_address_info
2025-02-25 19:03:21,287 - INFO - Closing Application...
2025-02-25 19:03:21,301 - INFO - Closing down clientserver connection
2025-02-25 19:09:04,756 - INFO - Starting Application...
2025-02-25 19:09:04,757 - INFO - Validating dataset_one with Pydantic.
2025-02-25 19:09:10,874 - ERROR - 1 validation error for EmployeeExpertiseCalls
calls_made
  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-54, input_type=int]
    For further information visit https://errors.pydantic.dev/2.10/v/greater_than_equal | Row: {'id': 1, 'area': 'IT', 'calls_made': -54, 'calls_successful': 41} 
2025-02-25 19:09:10,874 - ERROR - 'NoneType' object has no attribute 'lower' | Row: {'id': 6, 'area': None, 'calls_made': 29, 'calls_successful': 24} 
2025-02-25 19:09:10,884 - WARNING - A total of 2 invalid records excluded from dataset dataset_one
2025-02-25 19:09:11,067 - INFO - Validating dataset_two with Pydantic.
2025-02-25 19:09:11,511 - INFO - There were no invalid records found in dataset_two
2025-02-25 19:09:11,609 - INFO - Processing outputs sequentially...
2025-02-25 19:09:11,734 - INFO - Processing output it data...
2025-02-25 19:09:33,443 - INFO - Successfully processed top 100 agents selling IT products.
2025-02-25 19:09:33,443 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 19:09:50,420 - INFO - Processing output marketing address info...
2025-02-25 19:09:50,463 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 19:10:07,098 - INFO - Started processing department breakdown...
2025-02-25 19:10:26,609 - INFO - Writing Output department_breakdown to location: data/output/department_breakdown
2025-02-25 19:10:43,569 - INFO - Closing Application...
2025-02-25 19:10:43,589 - INFO - Closing down clientserver connection
2025-02-25 19:17:50,593 - INFO - Starting Application...
2025-02-25 19:17:50,602 - INFO - Validating dataset_one with Pydantic.
2025-02-25 19:17:56,935 - INFO - There were no invalid records found in dataset_one
2025-02-25 19:17:57,066 - INFO - Validating dataset_two with Pydantic.
2025-02-25 19:17:57,435 - INFO - There were no invalid records found in dataset_two
2025-02-25 19:17:57,543 - INFO - Processing outputs sequentially...
2025-02-25 19:17:57,701 - INFO - Processing output it data...
2025-02-25 19:18:19,698 - INFO - Successfully processed top 100 agents selling IT products.
2025-02-25 19:18:19,698 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 19:18:36,669 - INFO - Processing output marketing address info...
2025-02-25 19:18:36,730 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 19:18:52,485 - INFO - Started processing department breakdown...
2025-02-25 19:19:11,695 - INFO - Writing Output department_breakdown to location: data/output/department_breakdown
2025-02-25 19:19:33,633 - INFO - Closing Application...
2025-02-25 19:19:33,647 - INFO - Closing down clientserver connection
2025-02-25 20:35:51,119 - INFO - Starting Application...
2025-02-25 20:35:51,119 - INFO - Validating dataset_one with Pydantic.
2025-02-25 20:35:58,391 - INFO - There were no invalid records found in dataset_one
2025-02-25 20:35:58,576 - INFO - Validating dataset_two with Pydantic.
2025-02-25 20:35:59,004 - INFO - There were no invalid records found in dataset_two
2025-02-25 20:35:59,098 - INFO - Processing outputs sequentially...
2025-02-25 20:35:59,231 - INFO - Processing output it data...
2025-02-25 20:36:33,824 - INFO - Closing down clientserver connection
2025-02-25 20:37:26,360 - INFO - Starting Application...
2025-02-25 20:37:26,360 - INFO - Validating dataset_one with Pydantic.
2025-02-25 20:37:32,821 - INFO - There were no invalid records found in dataset_one
2025-02-25 20:37:33,105 - INFO - Validating dataset_two with Pydantic.
2025-02-25 20:37:33,403 - INFO - There were no invalid records found in dataset_two
2025-02-25 20:37:33,501 - INFO - Processing outputs sequentially...
2025-02-25 20:37:33,632 - INFO - Processing output it data...
2025-02-25 20:38:06,949 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 20:38:11,830 - INFO - Error while receiving.
Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
RuntimeError: reentrant call inside <_io.BufferedReader name=580>
2025-02-25 20:38:11,834 - INFO - Closing down clientserver connection
2025-02-25 20:38:11,834 - ERROR - Exception while sending command.
Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
RuntimeError: reentrant call inside <_io.BufferedReader name=580>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
2025-02-25 20:38:11,840 - INFO - Error while receiving.
Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Users\be_al\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\context.py", line 381, in signal_handler
    self.cancelAllJobs()
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\context.py", line 2446, in cancelAllJobs
    self._jsc.sc().cancelAllJobs()
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\errors\exceptions\captured.py", line 179, in deco
    return f(*a, **kw)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o16.sc
2025-02-25 20:38:11,847 - INFO - Closing down clientserver connection
2025-02-25 20:38:11,848 - ERROR - Exception while sending command.
Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Users\be_al\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\context.py", line 381, in signal_handler
    self.cancelAllJobs()
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\context.py", line 2446, in cancelAllJobs
    self._jsc.sc().cancelAllJobs()
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\errors\exceptions\captured.py", line 179, in deco
    return f(*a, **kw)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o16.sc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
2025-02-25 20:38:11,853 - INFO - Closing down clientserver connection
2025-02-25 20:38:11,892 - INFO - Closing down clientserver connection
2025-02-25 20:39:58,747 - INFO - Starting Application...
2025-02-25 20:39:58,747 - INFO - Validating dataset_one with Pydantic.
2025-02-25 20:40:04,949 - INFO - There were no invalid records found in dataset_one
2025-02-25 20:40:05,157 - INFO - Validating dataset_two with Pydantic.
2025-02-25 20:40:05,548 - INFO - There were no invalid records found in dataset_two
2025-02-25 20:40:05,644 - INFO - Processing outputs sequentially...
2025-02-25 20:40:05,776 - INFO - Processing output it data...
2025-02-25 20:40:39,874 - CRITICAL - Stopping the application. The data in dataset one and dataset two needs to be checked.
2025-02-25 20:40:39,902 - INFO - Closing down clientserver connection
2025-02-25 20:41:15,492 - INFO - Starting Application...
2025-02-25 20:41:15,493 - INFO - Validating dataset_one with Pydantic.
2025-02-25 20:41:21,764 - INFO - There were no invalid records found in dataset_one
2025-02-25 20:41:21,967 - INFO - Validating dataset_two with Pydantic.
2025-02-25 20:41:22,328 - INFO - There were no invalid records found in dataset_two
2025-02-25 20:41:22,440 - INFO - Processing outputs sequentially...
2025-02-25 20:41:22,578 - INFO - Processing output it data...
2025-02-25 20:41:57,077 - CRITICAL - Stopping the application. The data in dataset one and dataset two needs to be checked.
2025-02-25 20:41:57,077 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 20:42:02,980 - INFO - Error while receiving.
Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
RuntimeError: reentrant call inside <_io.BufferedReader name=504>
2025-02-25 20:42:02,982 - INFO - Closing down clientserver connection
2025-02-25 20:42:02,983 - ERROR - Exception while sending command.
Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
RuntimeError: reentrant call inside <_io.BufferedReader name=504>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
2025-02-25 20:42:02,988 - INFO - Error while receiving.
Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Users\be_al\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\context.py", line 381, in signal_handler
    self.cancelAllJobs()
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\context.py", line 2446, in cancelAllJobs
    self._jsc.sc().cancelAllJobs()
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\errors\exceptions\captured.py", line 179, in deco
    return f(*a, **kw)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o16.sc
2025-02-25 20:42:02,993 - INFO - Closing down clientserver connection
2025-02-25 20:42:02,994 - ERROR - Exception while sending command.
Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Users\be_al\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\context.py", line 381, in signal_handler
    self.cancelAllJobs()
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\context.py", line 2446, in cancelAllJobs
    self._jsc.sc().cancelAllJobs()
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\pyspark\errors\exceptions\captured.py", line 179, in deco
    return f(*a, **kw)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o16.sc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "C:\Users\be_al\Github\abn_amro\venv\lib\site-packages\py4j\clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
2025-02-25 20:42:02,999 - INFO - Closing down clientserver connection
2025-02-25 20:42:03,030 - INFO - Closing down clientserver connection
2025-02-25 21:22:25,438 - INFO - Starting Application...
2025-02-25 21:22:25,440 - INFO - Validating dataset_one with Pydantic.
2025-02-25 21:22:33,458 - INFO - There were no invalid records found in dataset_one
2025-02-25 21:22:33,622 - INFO - Validating dataset_two with Pydantic.
2025-02-25 21:22:33,907 - INFO - There were no invalid records found in dataset_two
2025-02-25 21:22:34,009 - INFO - Processing outputs sequentially...
2025-02-25 21:22:34,126 - INFO - Processing Output it data...
2025-02-25 21:22:54,954 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 21:22:54,954 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 21:23:12,163 - INFO - Closing Application...
2025-02-25 21:23:12,183 - INFO - Closing down clientserver connection
2025-02-25 21:25:02,869 - INFO - Starting Application...
2025-02-25 21:25:02,869 - INFO - Validating dataset_one with Pydantic.
2025-02-25 21:25:09,862 - INFO - There were no invalid records found in dataset_one
2025-02-25 21:25:10,001 - INFO - Validating dataset_two with Pydantic.
2025-02-25 21:25:10,291 - INFO - There were no invalid records found in dataset_two
2025-02-25 21:25:10,389 - INFO - Processing outputs sequentially...
2025-02-25 21:25:10,536 - INFO - Processing Output it data...
2025-02-25 21:25:32,685 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 21:25:32,685 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 21:25:51,685 - INFO - Closing down clientserver connection
2025-02-25 21:26:54,593 - INFO - Starting Application...
2025-02-25 21:26:54,601 - INFO - Validating dataset_one with Pydantic.
2025-02-25 21:27:01,109 - INFO - There were no invalid records found in dataset_one
2025-02-25 21:27:01,384 - INFO - Validating dataset_two with Pydantic.
2025-02-25 21:27:01,793 - INFO - There were no invalid records found in dataset_two
2025-02-25 21:27:01,892 - INFO - Processing outputs sequentially...
2025-02-25 21:27:02,048 - INFO - Processing Output it data...
2025-02-25 21:27:25,951 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 21:27:25,953 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 21:27:45,015 - INFO - Processing Output marketing address info...
2025-02-25 21:27:45,082 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 21:28:06,918 - INFO - Closing down clientserver connection
2025-02-25 21:30:46,746 - INFO - Starting Application...
2025-02-25 21:30:46,746 - INFO - Validating dataset_one with Pydantic.
2025-02-25 21:30:53,548 - INFO - There were no invalid records found in dataset_one
2025-02-25 21:30:53,731 - INFO - Validating dataset_two with Pydantic.
2025-02-25 21:30:54,083 - INFO - There were no invalid records found in dataset_two
2025-02-25 21:30:54,204 - INFO - Processing outputs sequentially...
2025-02-25 21:30:54,352 - INFO - Processing Output it data...
2025-02-25 21:31:16,432 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 21:31:16,434 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 21:31:33,833 - INFO - Processing Output marketing address info...
2025-02-25 21:31:34,129 - INFO - Closing down clientserver connection
2025-02-25 21:49:57,058 - INFO - Starting Application...
2025-02-25 21:49:57,062 - INFO - Validating dataset_one with Pydantic.
2025-02-25 21:50:03,230 - INFO - There were no invalid records found in dataset_one
2025-02-25 21:50:03,402 - INFO - Validating dataset_two with Pydantic.
2025-02-25 21:50:03,720 - INFO - There were no invalid records found in dataset_two
2025-02-25 21:50:03,822 - INFO - Processing outputs sequentially...
2025-02-25 21:50:03,949 - INFO - Processing Output it data...
2025-02-25 21:50:17,142 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 21:50:17,143 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 21:50:29,246 - INFO - Processing Output marketing address info...
2025-02-25 21:50:29,323 - INFO - Closing down clientserver connection
2025-02-25 21:51:03,463 - INFO - Starting Application...
2025-02-25 21:51:03,463 - INFO - Validating dataset_one with Pydantic.
2025-02-25 21:51:08,927 - INFO - There were no invalid records found in dataset_one
2025-02-25 21:51:09,057 - INFO - Validating dataset_two with Pydantic.
2025-02-25 21:51:09,512 - INFO - There were no invalid records found in dataset_two
2025-02-25 21:51:09,614 - INFO - Processing outputs sequentially...
2025-02-25 21:51:09,734 - INFO - Processing Output it data...
2025-02-25 21:51:26,743 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 21:51:26,743 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 21:51:40,521 - INFO - Processing Output marketing address info...
2025-02-25 21:51:54,393 - INFO - Sucessfully processed addresses and zip codes of employees selling marketing products.
2025-02-25 21:51:54,395 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 21:52:07,102 - INFO - Processing department breakdown...
2025-02-25 21:52:07,382 - INFO - Closing down clientserver connection
2025-02-25 21:52:57,449 - INFO - Starting Application...
2025-02-25 21:52:57,449 - INFO - Validating dataset_one with Pydantic.
2025-02-25 21:53:01,177 - INFO - There were no invalid records found in dataset_one
2025-02-25 21:53:01,330 - INFO - Validating dataset_two with Pydantic.
2025-02-25 21:53:01,686 - INFO - There were no invalid records found in dataset_two
2025-02-25 21:53:01,770 - INFO - Processing outputs sequentially...
2025-02-25 21:53:01,877 - INFO - Processing Output it data...
2025-02-25 21:53:15,086 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 21:53:15,086 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 21:53:27,718 - INFO - Processing Output marketing address info...
2025-02-25 21:53:39,667 - INFO - Sucessfully processed addresses and zip codes of employees selling marketing products.
2025-02-25 21:53:39,668 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 21:53:51,436 - INFO - Processing department breakdown...
2025-02-25 21:54:02,802 - INFO - Sucessfully processed sales and calls success rate per department.
2025-02-25 21:54:02,803 - INFO - Writing Output department_breakdown to location: data/output/department_breakdown
2025-02-25 21:54:14,129 - INFO - Closing Application...
2025-02-25 21:54:14,143 - INFO - Closing down clientserver connection
2025-02-25 21:55:34,126 - INFO - Validating dataset_one with Pydantic.
2025-02-25 21:55:37,495 - INFO - There were no invalid records found in dataset_one
2025-02-25 21:55:37,592 - INFO - Validating dataset_two with Pydantic.
2025-02-25 21:55:37,748 - INFO - There were no invalid records found in dataset_two
2025-02-25 21:55:37,808 - INFO - Processing outputs sequentially...
2025-02-25 21:55:37,915 - INFO - Processing Output it data...
2025-02-25 21:55:48,355 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 21:55:48,356 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 21:55:59,864 - INFO - Processing Output marketing address info...
2025-02-25 21:56:11,226 - INFO - Sucessfully processed addresses and zip codes of employees selling marketing products.
2025-02-25 21:56:11,227 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 21:56:22,490 - INFO - Processing department breakdown...
2025-02-25 21:56:35,140 - INFO - Sucessfully processed sales and calls success rate per department.
2025-02-25 21:56:35,154 - INFO - Writing Output department_breakdown to location: data/output/department_breakdown
2025-02-25 21:56:47,045 - INFO - Closing Application...
2025-02-25 21:56:47,068 - INFO - Closing down clientserver connection
2025-02-25 22:00:51,172 - INFO - Validating dataset_one with Pydantic.
2025-02-25 22:00:54,689 - INFO - There were no invalid records found in dataset_one
2025-02-25 22:00:54,806 - INFO - Validating dataset_two with Pydantic.
2025-02-25 22:00:55,031 - INFO - There were no invalid records found in dataset_two
2025-02-25 22:00:55,112 - INFO - Processing outputs sequentially...
2025-02-25 22:00:55,215 - INFO - Processing Output it data...
2025-02-25 22:01:06,931 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 22:01:06,932 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 22:01:19,190 - INFO - Processing Output marketing address info...
2025-02-25 22:01:19,270 - INFO - Closing down clientserver connection
2025-02-25 22:03:08,758 - INFO - Validating dataset_one with Pydantic.
2025-02-25 22:03:12,212 - INFO - There were no invalid records found in dataset_one
2025-02-25 22:03:12,309 - INFO - Validating dataset_two with Pydantic.
2025-02-25 22:03:12,531 - INFO - There were no invalid records found in dataset_two
2025-02-25 22:03:12,609 - INFO - Processing outputs sequentially...
2025-02-25 22:03:12,702 - INFO - Processing Output it data...
2025-02-25 22:03:23,927 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 22:03:23,927 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 22:03:35,576 - INFO - Processing Output marketing address info...
2025-02-25 22:03:46,278 - WARNING - Check logs for incorrect addresses and/or zip codes.
2025-02-25 22:03:46,278 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 22:03:57,159 - INFO - Processing department breakdown...
2025-02-25 22:04:08,993 - CRITICAL - Stopping the application. Success Rate above 100 percent is not possible.
 The data in datasetsone and two needs to be checked.
2025-02-25 22:04:09,022 - INFO - Closing down clientserver connection
2025-02-25 22:08:25,821 - INFO - Validating dataset_one with Pydantic.
2025-02-25 22:08:29,809 - INFO - There were no invalid records found in dataset_one
2025-02-25 22:08:29,907 - INFO - Validating dataset_two with Pydantic.
2025-02-25 22:08:30,112 - INFO - There were no invalid records found in dataset_two
2025-02-25 22:08:30,181 - INFO - Processing outputs sequentially...
2025-02-25 22:08:30,291 - INFO - Processing Output it data...
2025-02-25 22:08:40,600 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 22:08:40,600 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 22:08:52,129 - INFO - Processing Output marketing address info...
2025-02-25 22:09:03,797 - INFO - Sucessfully processed addresses and zip codes of employees selling marketing products.
2025-02-25 22:09:03,797 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 22:09:14,810 - INFO - Processing department breakdown...
2025-02-25 22:09:26,275 - INFO - Sucessfully processed sales and calls success rate per department.
2025-02-25 22:09:26,275 - INFO - Writing Output department_breakdown to location: data/output/department_breakdown
2025-02-25 22:09:37,902 - INFO - Closing Application...
2025-02-25 22:09:37,922 - INFO - Closing down clientserver connection
2025-02-25 23:28:23,269 - INFO - Validating dataset_one with Pydantic.
2025-02-25 23:28:27,924 - INFO - There were no invalid records found in dataset_one
2025-02-25 23:28:28,021 - INFO - Validating dataset_two with Pydantic.
2025-02-25 23:28:28,249 - INFO - There were no invalid records found in dataset_two
2025-02-25 23:28:28,306 - INFO - Processing Outputs sequentially...
2025-02-25 23:28:28,413 - INFO - Processing top 3 employees per department...
2025-02-25 23:28:28,776 - INFO - Closing down clientserver connection
2025-02-25 23:31:01,137 - INFO - Validating dataset_one with Pydantic.
2025-02-25 23:31:04,509 - INFO - There were no invalid records found in dataset_one
2025-02-25 23:31:04,616 - INFO - Validating dataset_two with Pydantic.
2025-02-25 23:31:04,857 - INFO - There were no invalid records found in dataset_two
2025-02-25 23:31:04,928 - INFO - Processing Outputs sequentially...
2025-02-25 23:31:05,013 - INFO - Processing top 3 employees per department...
2025-02-25 23:31:05,180 - INFO - Closing down clientserver connection
2025-02-25 23:34:41,843 - INFO - Validating dataset_one with Pydantic.
2025-02-25 23:34:45,317 - INFO - There were no invalid records found in dataset_one
2025-02-25 23:34:45,421 - INFO - Validating dataset_two with Pydantic.
2025-02-25 23:34:45,634 - INFO - There were no invalid records found in dataset_two
2025-02-25 23:34:45,691 - INFO - Processing Outputs sequentially...
2025-02-25 23:34:45,781 - INFO - Processing top 3 employees per department...
2025-02-25 23:34:45,957 - INFO - Writing Output top_three_per_department to location: data/output/top_three_per_department
2025-02-25 23:35:01,136 - INFO - Closing Application...
2025-02-25 23:35:01,147 - INFO - Closing down clientserver connection
2025-02-25 23:50:29,450 - INFO - Validating dataset_one with Pydantic.
2025-02-25 23:50:34,447 - INFO - There were no invalid records found in dataset_one
2025-02-25 23:50:34,547 - INFO - Validating dataset_two with Pydantic.
2025-02-25 23:50:34,794 - INFO - There were no invalid records found in dataset_two
2025-02-25 23:50:34,869 - INFO - Processing Outputs sequentially...
2025-02-25 23:50:34,978 - INFO - Processing top 3 employees per department...
2025-02-25 23:50:35,183 - INFO - Writing Output top_three_per_department to location: data/output/top_three_per_department
2025-02-25 23:50:49,952 - INFO - Closing Application...
2025-02-25 23:50:49,971 - INFO - Closing down clientserver connection
2025-02-25 23:51:15,025 - INFO - Validating dataset_one with Pydantic.
2025-02-25 23:51:18,427 - INFO - There were no invalid records found in dataset_one
2025-02-25 23:51:18,511 - INFO - Validating dataset_two with Pydantic.
2025-02-25 23:51:18,736 - INFO - There were no invalid records found in dataset_two
2025-02-25 23:51:18,812 - INFO - Processing Outputs sequentially...
2025-02-25 23:51:18,901 - INFO - Processing Output it data...
2025-02-25 23:51:31,096 - INFO - Successfully processed top 100 employees selling it products.
2025-02-25 23:51:31,099 - INFO - Writing Output it_data to location: data/output/it_data
2025-02-25 23:51:42,591 - INFO - Processing Output marketing address info...
2025-02-25 23:51:52,963 - INFO - Sucessfully processed addresses and zip codes of employees selling marketing products.
2025-02-25 23:51:52,964 - INFO - Writing Output marketing_address_info to location: data/output/marketing_address_info
2025-02-25 23:52:04,500 - INFO - Processing department breakdown...
2025-02-25 23:52:16,356 - INFO - Sucessfully processed sales and calls success rate per department.
2025-02-25 23:52:16,356 - INFO - Writing Output department_breakdown to location: data/output/department_breakdown
2025-02-25 23:52:27,812 - INFO - Processing top 3 employees per department...
2025-02-25 23:52:27,921 - INFO - Writing Output top_three_per_department to location: data/output/top_three_per_department
2025-02-25 23:52:39,216 - INFO - Closing Application...
2025-02-25 23:52:39,230 - INFO - Closing down clientserver connection
